// <auto-generated />
using System;
using BloodBankMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodBankMVC.Migrations
{
    [DbContext(typeof(BloodBankContext))]
    [Migration("20260401103721_Added Phone No Column")]
    partial class AddedPhoneNoColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodBankMVC.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DonorId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestorId")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("RequestorId");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("BloodBankMVC.Models.BloodGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodGroupName")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("BloodGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodGroupName = "A+"
                        },
                        new
                        {
                            Id = 2,
                            BloodGroupName = "A-"
                        },
                        new
                        {
                            Id = 3,
                            BloodGroupName = "B+"
                        },
                        new
                        {
                            Id = 4,
                            BloodGroupName = "B-"
                        },
                        new
                        {
                            Id = 5,
                            BloodGroupName = "AB+"
                        },
                        new
                        {
                            Id = 6,
                            BloodGroupName = "AB-"
                        },
                        new
                        {
                            Id = 7,
                            BloodGroupName = "O+"
                        },
                        new
                        {
                            Id = 8,
                            BloodGroupName = "O-"
                        });
                });

            modelBuilder.Entity("BloodBankMVC.Models.BloodInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroupId");

                    b.ToTable("BloodInventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodGroupId = 1,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 2,
                            BloodGroupId = 2,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            BloodGroupId = 3,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 4,
                            BloodGroupId = 4,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 5,
                            BloodGroupId = 5,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 6,
                            BloodGroupId = 6,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 7,
                            BloodGroupId = 7,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 8,
                            BloodGroupId = 8,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("BloodBankMVC.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BloodGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DonateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroupId");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("BloodBankMVC.Models.Requestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BloodGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitRequested")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroupId");

                    b.ToTable("Requestors");
                });

            modelBuilder.Entity("BloodBankMVC.Models.Audit", b =>
                {
                    b.HasOne("BloodBankMVC.Models.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId");

                    b.HasOne("BloodBankMVC.Models.Requestor", "Requestor")
                        .WithMany()
                        .HasForeignKey("RequestorId");

                    b.Navigation("Donor");

                    b.Navigation("Requestor");
                });

            modelBuilder.Entity("BloodBankMVC.Models.BloodInventory", b =>
                {
                    b.HasOne("BloodBankMVC.Models.BloodGroup", "BloodGroup")
                        .WithMany()
                        .HasForeignKey("BloodGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodGroup");
                });

            modelBuilder.Entity("BloodBankMVC.Models.Donor", b =>
                {
                    b.HasOne("BloodBankMVC.Models.BloodGroup", "BloodGroup")
                        .WithMany()
                        .HasForeignKey("BloodGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodGroup");
                });

            modelBuilder.Entity("BloodBankMVC.Models.Requestor", b =>
                {
                    b.HasOne("BloodBankMVC.Models.BloodGroup", "BloodGroup")
                        .WithMany()
                        .HasForeignKey("BloodGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
